insert into invoice (customerReference, invoiceNumber, description, amount) values ('cr 1' ,'1', 'Invoice Description 1',1000000); 
insert into invoice (customerReference, invoiceNumber, description, amount) values ('cr 2' ,'2', 'Invoice Description 2',1000000); 
insert into invoice (customerReference, invoiceNumber, description, amount) values ('cr 3' ,'3', 'Invoice Description 3',1000000); 
insert into invoice (customerReference, invoiceNumber, description, amount) values ('cr 4' ,'4', 'Invoice Description 4',1000000); 
insert into invoice (customerReference, invoiceNumber, description, amount) values ('cr 5' ,'5', 'Invoice Description 5',1000000); 
insert into invoice (customerReference, invoiceNumber, description, amount) values ('cr 6' ,'6', 'Invoice Description 6',1000000); 
insert into invoice (customerReference, invoiceNumber, description, amount) values ('cr 7' ,'7', 'Invoice Description 7',1000000); 
insert into invoice (customerReference, invoiceNumber, description, amount) values ('cr 8' ,'8', 'Invoice Description 8',1000000); 
insert into invoice (customerReference, invoiceNumber, description, amount) values ('cr 9' ,'9', 'Invoice Description 9',1000000); 
insert into invoice (customerReference, invoiceNumber, description, amount) values ('cr 10' ,'10', 'Invoice Description 10',1000000); 
insert into invoice (customerReference, invoiceNumber, description, amount) values ('cr 11' ,'11', 'Invoice Description 11',1000000); 
insert into invoice (customerReference, invoiceNumber, description, amount) values ('cr 12' ,'12', 'Invoice Description 12',1000000); 
insert into invoice (customerReference, invoiceNumber, description, amount) values ('cr 13' ,'13', 'Invoice Description 13',1000000); 
insert into invoice (customerReference, invoiceNumber, description, amount) values ('cr 14' ,'14', 'Invoice Description 14',1000000); 
insert into invoice (customerReference, invoiceNumber, description, amount) values ('cr 15' ,'15', 'Invoice Description 15',1000000); 
insert into invoice (customerReference, invoiceNumber, description, amount) values ('cr 16' ,'16', 'Invoice Description 16',1000000); 
insert into invoice (customerReference, invoiceNumber, description, amount) values ('cr 17' ,'17', 'Invoice Description 17',1000000); 
insert into invoice (customerReference, invoiceNumber, description, amount) values ('cr 18' ,'18', 'Invoice Description 18',1000000); 
insert into invoice (customerReference, invoiceNumber, description, amount) values ('cr 19' ,'19', 'Invoice Description 19',1000000); 
insert into invoice (customerReference, invoiceNumber, description, amount) values ('cr 20' ,'20', 'Invoice Description 20',1000000); 
insert into invoice (customerReference, invoiceNumber, description, amount) values ('cr 21' ,'21', 'Invoice Description 21',1000000); 
insert into invoice (customerReference, invoiceNumber, description, amount) values ('cr 22' ,'22', 'Invoice Description 22',1000000); 
insert into invoice (customerReference, invoiceNumber, description, amount) values ('cr 23' ,'23', 'Invoice Description 23',1000000); 
insert into invoice (customerReference, invoiceNumber, description, amount) values ('cr 24' ,'24', 'Invoice Description 24',1000000); 
insert into invoice (customerReference, invoiceNumber, description, amount) values ('cr 25' ,'25', 'Invoice Description 25',1000000); 
insert into invoice (customerReference, invoiceNumber, description, amount) values ('cr 26' ,'26', 'Invoice Description 26',1000000); 
insert into invoice (customerReference, invoiceNumber, description, amount) values ('cr 27' ,'27', 'Invoice Description 27',1000000); 
insert into invoice (customerReference, invoiceNumber, description, amount) values ('cr 28' ,'28', 'Invoice Description 28',1000000); 
insert into invoice (customerReference, invoiceNumber, description, amount) values ('cr 29' ,'29', 'Invoice Description 29',1000000); 

insert into item  (code, name, description, amount) values ('Item 1' ,'Item Name 1', 'Item  Description 1',1000000);
insert into item  (code, name, description, amount) values ('Item 2' ,'Item Name 2', 'Item  Description 2',1000000);
insert into item  (code, name, description, amount) values ('Item 3' ,'Item Name 3', 'Item  Description 3',1000000);
insert into item  (code, name, description, amount) values ('Item 4' ,'Item Name 4', 'Item  Description 4',1000000);
insert into item  (code, name, description, amount) values ('Item 5' ,'Item Name 5', 'Item  Description 5',1000000);
insert into item  (code, name, description, amount) values ('Item 6' ,'Item Name 6', 'Item  Description 6',1000000);
insert into item  (code, name, description, amount) values ('Item 7' ,'Item Name 7', 'Item  Description 7',1000000);
insert into item  (code, name, description, amount) values ('Item 8' ,'Item Name 8', 'Item  Description 8',1000000);
insert into item  (code, name, description, amount) values ('Item 9' ,'Item Name 9', 'Item  Description 9',1000000);
insert into item  (code, name, description, amount) values ('Item 10' ,'Item Name 10', 'Item  Description 10',1000000);
insert into item  (code, name, description, amount) values ('Item 11' ,'Item Name 11', 'Item  Description 11',1000000);
insert into item  (code, name, description, amount) values ('Item 12' ,'Item Name 12', 'Item  Description 12',1000000);
insert into item  (code, name, description, amount) values ('Item 13' ,'Item Name 13', 'Item  Description 13',1000000);
insert into item  (code, name, description, amount) values ('Item 14' ,'Item Name 14', 'Item  Description 14',1000000);
insert into item  (code, name, description, amount) values ('Item 15' ,'Item Name 15', 'Item  Description 15',1000000);
insert into item  (code, name, description, amount) values ('Item 16' ,'Item Name 16', 'Item  Description 16',1000000);
insert into item  (code, name, description, amount) values ('Item 17' ,'Item Name 17', 'Item  Description 17',1000000);
insert into item  (code, name, description, amount) values ('Item 18' ,'Item Name 18', 'Item  Description 18',1000000);
insert into item  (code, name, description, amount) values ('Item 19' ,'Item Name 19', 'Item  Description 19',1000000);
insert into item  (code, name, description, amount) values ('Item 20' ,'Item Name 20', 'Item  Description 20',1000000);
insert into item  (code, name, description, amount) values ('Item 21' ,'Item Name 21', 'Item  Description 21',1000000);
insert into item  (code, name, description, amount) values ('Item 22' ,'Item Name 22', 'Item  Description 22',1000000);
insert into item  (code, name, description, amount) values ('Item 23' ,'Item Name 23', 'Item  Description 23',1000000);
insert into item  (code, name, description, amount) values ('Item 24' ,'Item Name 24', 'Item  Description 24',1000000);
insert into item  (code, name, description, amount) values ('Item 25' ,'Item Name 25', 'Item  Description 25',1000000);
insert into item  (code, name, description, amount) values ('Item 26' ,'Item Name 26', 'Item  Description 26',1000000);
insert into item  (code, name, description, amount) values ('Item 27' ,'Item Name 27', 'Item  Description 27',1000000);
insert into item  (code, name, description, amount) values ('Item 28' ,'Item Name 28', 'Item  Description 28',1000000);
insert into item  (code, name, description, amount) values ('Item 29' ,'Item Name 29', 'Item  Description 29',1000000);
insert into item  (code, name, description, amount) values ('Item 30' ,'Item Name 30', 'Item  Description 30',1000000);

insert into customer (firstname, surname) values ('Andy', 'Smith');
insert into customer (firstname, surname) values ('Chiara', 'Pieruccu');
insert into customer (firstname, surname) values ('Jack', 'The Ripper');
insert into customer (firstname, surname) values ('Antonio', 'Montana');
insert into customer (firstname, surname) values ('Ozzy', 'Ozbourne');
insert into customer (firstname, surname) values ('James', 'Bell');
insert into customer (firstname, surname) values ('Lee', 'French');